### ISSUE TITLE
TypeError: Uncaught error: Cannot read property 'match' of undefined at getStateKey 

### ISSUE THREAD

**Issue by dankle** [jhudson8/smocks#10]
Get this problem when running smocks v3.2.1 with smocks-magellan-nightwatch v3.2.0.

Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'match' of undefined
    at getStateKey (/Users/dklever/Documents/Development/Repositories/collections/test/automation/node_modules/smocks-magellan-nightwatch/lib/multiport-state.js:38:22)
    at Object.module.exports.initialize (/Users/dklever/Documents/Development/Repositories/collections/test/automation/node_modules/smocks-magellan-nightwatch/lib/multiport-state.js:7:15)
    at connection.route.handler (/Users/dklever/Documents/Development/Repositories/collections/test/automation/node_modules/smocks/hapi.js:171:24)
    at Object.internals.handler (/Users/dklever/Documents/Development/Repositories/collections/test/automation/node_modules/smocks-magellan-nightwatch/node_modules/hapi/lib/handler.js:93:36)
    at /Users/dklever/Documents/Development/Repositories/collections/test/automation/node_modules/smocks-magellan-nightwatch/node_modules/hapi/lib/handler.js:28:23
    at internals.Protect.run (/Users/dklever/Documents/Development/Repositories/collections/test/automation/node_modules/smocks-magellan-nightwatch/node_modules/hapi/lib/protect.js:56:5)
    at exports.execute (/Users/dklever/Documents/Development/Repositories/collections/test/automation/node_modules/smocks-magellan-nightwatch/node_modules/hapi/lib/handler.js:22:22)
    at /Users/dklever/Documents/Development/Repositories/collections/test/automation/node_modules/smocks-magellan-nightwatch/node_modules/hapi/lib/request.js:370:13
    at iterate (/Users/dklever/Documents/Development/Repositories/collections/test/automation/node_modules/smocks-magellan-nightwatch/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/Users/dklever/Documents/Development/Repositories/collections/test/automation/node_modules/smocks-magellan-nightwatch/node_modules/hapi/node_modules/items/lib/index.js:27:25)

**Comment by dankle** [comment]
Running node v4.2.5
